platform :ios, '9.0'

target 'DataSourcee' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DataSourcee
	
    pod 'SwiftyJSON'
    pod 'Alamofire'
    pod 'SVProgressHUD'

end
